os: Visual Studio 2015

platform: x64

build: off

install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
  - choco install strawberryperl
  - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - git clone https://github.com/tadzik/rakudobrew %USERPROFILE%\rakudobrew
  - SET PATH=%USERPROFILE%\rakudobrew\bin;%PATH%
  - rakudobrew build moar 2017.07
  - rakudobrew build zef
  - cd %APPVEYOR_BUILD_FOLDER%
  - zef install Test::META
  - zef install Path::Iterator
  - zef install TAP::Harness
  - zef install Crypt::Random
  - zef install Crypt::Bcrypt
  - zef install DBIish
#  - zef install Bailador
#  - zef -v install https://github.com/Bailador/Bailador/archive/dev.tar.gz
  - zef install Email::Valid
  - zef install LWP::Simple
  - zef install IO::Socket::SSL
#  - zef install Redis
#  - zef install MongoDB

#  - zef install File::Directory::Tree
#  - zef install Log::Any
#  - zef --verbose --depsonly install .

#  - SET PATH=C:\Users\appveyor\rakudobrew\moar-2017.07\install\share\perl6\site\bin;%PATH%

test_script:
  - prove -v -e "perl6 -Ilib" t/
  #- prove6

shallow_clone: true
